services:
  web-scraper:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    container_name: rust-web-scraper

networks:
  default:
    name: scraper-network
